name: Testing the API
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Send GET request to the API to get the data from server.Its result will be in JSON. Store its response in a file
       run: |
         curl https://jsonplaceholder.typicode.com/todos/1 > outputfile.json 
         echo "Output is:"
         # cat outputfile.json

     - name: Fetch only a field say title from the API response.
       run: |
          TITLE=$(curl https://jsonplaceholder.typicode.com/todos/1 | jq -r '.title')
          echo "TITLE is: ${TITLE}"
     
     - name: API key
       run: |
         # .kuch API bolti h data chaiye? pehle API key btao.For API key, use -H "Authorization: Bearer <API_KEY_TOKEN>". Note <API_KEY_TOKEN> kbhi bhi workflow me ni likhte.usko pehle secret me store krte h
          TITLE=$(curl -H "Authorization: Bearer my-secret-key" https://api.example.com/data)
          echo "TITLE is: $TITLE"

     - name: POST API
       run: |
         # GET me server se data lete h. POST Me data bhejte h server ko.-X me btao kon sa method h, -H "Content-Type: application/json" means me json type ka data bhej rhi hu, -d means ye body ha data ki
         curl -X POST https://jsonplaceholder.typicode.com/posts \
         -H "Content-Type: application/json" \
         -d '{
           "title": "mera-title",
           "body": "mera content",
           "userId": 2
           }'
         curl https://jsonplaceholder.typicode.com/todos/2 > outputfile1.json | cat outputfile1.json
            
        
         
