name: Testing the API
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Send GET request to the API to get the data from server.Its result will be in JSON. Store this result in a file
       run: |
         curl https://jsonplaceholder.typicode.com/todos/1 > outputfile.json 
         cat outputfile.json
