name: Testing the API
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Send GET request to the API to get the data from server.Its result will be in JSON. Store its response in a file
       run: |
         curl https://jsonplaceholder.typicode.com/todos/1 > outputfile.json 
         echo "Output is:"
         cat outputfile.json

     - name: Fetch only a field say title from the API response.
       run: |
          TITLE=$(curl https://jsonplaceholder.typicode.com/todos/1 | jq -r '.title')
          echo "TITLE is: ${TITLE}"
     
     - name: API key
       run: |
         # .kuch API bolti h data chaiye? pehle API key btao.For API key, use -H "Authorization: Bearer <API_KEY_TOKEN>". Note <API_KEY_TOKEN> kbhi bhi workflow me ni likhte.usko pehle secret me store krte h
          TITLE=$(curl -H "Authorization: Bearer my-secret-key" https://jsonplaceholder.typicode.com/todos/1)
          echo "TITLE is: $TITLE"

     - name: POST API
       run: |
         # GET me server se data lete h. POST Me data bhejte h server ko.-X me btao kon sa method h, -H "Content-Type: application/json" means me json type ka data bhej rhi hu, -d means ye body ha data ki
         curl -X POST https://jsonplaceholder.typicode.com/posts \
         -H "Content-Type: application/json" \
         -d '{
           "title": "mera-title",
           "body": "mera content",
           "userId": 2
           }'
        
         #To Verify whether ye data post hua bhi h server pr ya ni
         curl https://jsonplaceholder.typicode.com/todos/2 > outputfile1.json | echo "After POST result is:" | cat outputfile1.json
         
     - name: response control krna API ka
       run: |
         curl https://jsonplaceholder.typicode.com/todos/1 > outputfile1.json
         echo "redirection ka output h:"
         cat outputfile1.json

         # jo kaam redirection se kra rhe h vo same kaam -o flag se kra rhe h.API ka response outputfile4.json me aa k store ho jaega
         curl -o outputfile4.json https://jsonplaceholder.typicode.com/todos/1
         echo "o flag ka output h:"
         cat outputfile4.json

         # -o /dev/null means output ya response ko discard kr do
         echo " devnull ko use kr k $(curl -o /dev/null https://jsonplaceholder.typicode.com/todos/2)"
         
     - name: response control krna API ka
       run: |
         # -w "%{http_code}" likhte h status code capture krne k liye
         
         curl -o statusfile.json -w "%{http_code}" https://jsonplaceholder.typicode.com/todos/1
         cat statusfile.json
         # if [ "$STATUS" -ne 200 ]; then
         #  echo "API is failed bcz 200 nhi aya response"
         #  exit 1
         # fi
         # echo "continue next"

        
             
           
        
         
